services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brightside\TransliterateSlugger\:
    resource: "../Classes/*"

  Brightside\TransliterateSlugger\EventListener\UniversalSlugInjector:
    tags:
      - name: event.listener
        identifier: "transliterate-slugger-native-injector"
        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent
